from __future__ import annotations
__all__ = ['Tensor']
class Tensor:
    @staticmethod
    def _pybind11_conduit_v1_(*args, **kwargs):
        ...
    @staticmethod
    def ones(arg0: list[int]) -> Tensor:
        ...
    @staticmethod
    def zeros(arg0: list[int]) -> Tensor:
        ...
    def __init__(self, arg0: list[int]) -> None:
        ...
    def add(self, arg0: Tensor) -> Tensor:
        ...
    def matmul(self, arg0: Tensor) -> Tensor:
        ...
    def print(self) -> None:
        ...
