

all: main test

test:
	g++ -std=c++17 -o test tensor.cpp utils.cpp z_test.cpp -I "C:\Users\pablo\anaconda3\envs\base-3.9\Library\include" -O3 -I "C:\Users\pablo\anaconda3\envs\base-3.9\Library\include" -L "C:\Users\pablo\anaconda3\envs\base-3.9\Library\lib" -lopenblas

clean:
	del test.exe